services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: running-nextjs-Dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

