export const REGIONS = {
  GLOBAL: 'Global',
  EUROPE: 'Europe',
  AMERICA: {
    NORTH: 'North America',
    OTHER: 'South & Central America',
  },
  ASIA: 'Asia, ex-China',
  OCEANIA: 'Oceania',
  AFRICA: 'Africa',
  CZ: 'China',
  US: 'USA',
  CD: 'DRC',
};

export const SETTINGS = {
  [REGIONS.GLOBAL]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD', // ?
    'IO Region': 'Global',
    'Unido Region': 'Global',
    'CO Region': 'GLOBAL',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 5,
    'Coefficients for Recycling by Region': 1,
    'Corporate Rate 2020': 0.24,
    'Sum Global': false, // ?
  },
  [REGIONS.EUROPE]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'Europe',
    'Unido Region': 'Europe',
    'CO Region': 'EUROPE',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.22,
    'Corporate Rate 2020': 0.2,
    'Sum Global': true,
  },
  [REGIONS.AMERICA.NORTH]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'North America',
    'Unido Region': 'North America',
    'CO Region': 'NORTH AMERICA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.19,
    'Corporate Rate 2020': 0.26,
    'Sum Global': true,
  },
  [REGIONS.AMERICA.OTHER]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'South & Central America',
    'Unido Region': 'South & Central America',
    'CO Region': 'SOUTH & CENTRAL AMERICA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.02,
    'Corporate Rate 2020': 0.28,
    'Sum Global': true,
  },
  [REGIONS.ASIA]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'Asia, ex-China',
    'Unido Region': 'Asia, ex-China',
    'CO Region': 'ASIA, EX-CHINA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.21,
    'Corporate Rate 2020': 0.2,
    'Sum Global': true,
  },
  [REGIONS.OCEANIA]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'Oceania',
    'Unido Region': 'Oceania',
    'CO Region': 'OCEANIA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.09,
    'Corporate Rate 2020': 0.24,
    'Sum Global': true,
  },
  [REGIONS.AFRICA]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'Africa',
    'Unido Region': 'Africa',
    'CO Region': 'AFRICA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.01,
    'Corporate Rate 2020': 0.29,
    'Sum Global': true,
  },
  [REGIONS.CZ]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'China',
    'Unido Region': 'China',
    'CO Region': 'CHINA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.26,
    'Corporate Rate 2020': 0.25,
    'Sum Global': true,
  },
  [REGIONS.US]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'North America',
    'Unido Region': 'North America',
    'CO Region': 'USA',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.19,
    'Corporate Rate 2020': 0.26,
    'Sum Global': false,
  },
  [REGIONS.CD]: {
    'Study': 'Global Study', // ?
    'IO Source': 'OECD',
    'IO Region': 'Africa',
    'Unido Region': 'Africa',
    'CO Region': 'DRC',
    'Currency': 'USD',
    'Industry Source': 'UNIDO 2',
    'Last year': 2019,
    'Coefficients for European Union - 28 countries': 1,
    'Coefficients for Recycling by Region': 0.01,
    'Corporate Rate 2020': 0.29,
    'Sum Global': false,
  },
};
