on:
  push:
     branches:
       - main

jobs:
  balena_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install dependencies
      run: npm i
    - name: Build with Next.js
      run: npm build
    - name: Prepare to publish
      run: ./tools/sh/postbuild.sh
    - name: Balena Deploy
      uses: bekriebel/balena-cli-action@v1
      if: success()
      with:
        balena_api_token: ${{ secrets.BALENA_TOKEN }}
        balena_command: "deploy g_weareour_tech/pi-2 --logs"
        application_path: "./.next/standalone"
